config/routes.rb
Rails.application.routes.draw do

  # Sections
  resources :sections, only: [:show, :edit, :update] do
    resources :chapters, only: [:new, :create]
    resources :problems, only: [:index, :new, :create]
  end

  # Chapters
  resources :chapters, only: [:show, :update, :edit, :destroy] do
    member do
      get :all
      put :put_online
      put :mark_submission_prerequisite
      put :unmark_submission_prerequisite
      put :order
      put :read
    end
    collection do
      get :stats
    end
    resources :theories, only: [:show, :new, :create]
    resources :questions, only: [:show, :new, :create]
  end

  # Prerequisites
  resources :prerequisites, only: [:index, :create, :destroy]

  # Theories
  resources :theories, only: [:update, :edit, :destroy] do
    member do
      put :order
      put :put_online
      put :read
      put :unread
    end
  end

  # Questions
  resources :questions, only: [:update, :edit, :destroy] do
    member do
      put :order
      put :put_online
      get :edit_explanation
      patch :update_explanation
      get :manage_items
      get :show_answer # only via JS
      get :hide_answer # only via JS
      get :check_answer # only via JS
    end
    resources :items, only: [:create]
  end
  
  # Items
  resources :items, only: [:update, :destroy] do
    member do
      put :correct
      put :uncorrect
      put :order
    end
  end
  
  # Problems
  resources :problems, only: [:update, :edit, :destroy, :show] do
    member do
      put :delete_prerequisite
      post :add_prerequisite
      put :order
      put :put_online
      get :edit_explanation
      get :edit_markscheme
      patch :update_explanation
      patch :update_markscheme
      post :add_virtualtest
      get :manage_externalsolutions
      get :mark_favorite # only via JS
      get :unmark_favorite # only via JS
      put :mark_reviewed
      put :unmark_reviewed
    end
    resources :submissions, only: [:show, :new, :create, :index] # 'index' only via JS
    resources :externalsolutions, only: [:create]
  end
  
  resources :solvedproblems, only: [:index]

  # Submissions
  resources :submissions, only: [:update, :destroy] do
    member do
      patch :send_draft
      put :read
      put :unread
      put :star
      put :unstar
      put :update_score
      put :mark_wrong
      put :mark_correct
      get :reserve # only via JS
      get :unreserve # only via JS
      post :search_script # only via JS
      get :next_good
      get :prev_good
    end
    collection do
      get :all
      get :allmy
      get :allnew
      get :allmynew
      get :allhidden
    end
    resources :corrections, only: [:create]
    resources :suspicions, only: [:create]
    resources :starproposals, only: [:create]
  end
  
  # External solutions
  resources :externalsolutions, only: [:update, :destroy] do
    resources :extracts, only: [:create]
  end
  
  # Extracts
  resources :extracts, only: [:update, :destroy]
  
  # Suspicions
  resources :suspicions, only: [:index, :destroy, :update]
  
  # Star proposals
  resources :starproposals, only: [:index, :destroy, :update]
  
  # Virtual tests
  resources :virtualtests do
    member do
      put :put_online
      put :begin_test
    end
  end
  
  # Contests
  resources :contests do
    member do
      put :put_online
      get :cutoffs
      post :define_cutoffs
      put :follow
      get :unfollow # Get because it should be doable via email link
      patch :add_organizer
      put :remove_organizer
    end
    resources :contestproblems, only: [:new, :create]
  end
  
  # Contest problems
  resources :contestproblems, only: [:show, :edit, :update, :destroy] do
    member do
      put :publish_results
      put :authorize_corrections
      put :unauthorize_corrections
    end
    resources :contestsolutions, only: [:show, :create]
  end
  
  # Contest solutions
  resources :contestsolutions, only: [:update, :destroy] do
    member do
      get :reserve # only via JS
      get :unreserve # only via JS
    end
  end
  
  # Contest corrections
  resources :contestcorrections, only: [:update]
  
  # Subjects
  resources :subjects, only: [:index, :show, :new, :create, :update, :destroy] do
    member do
      put :migrate
      put :follow
      get :unfollow # Get because it should be doable via email link
    end
    resources :messages, only: [:create]
  end
  
  # Messages
  resources :messages, only: [:update, :destroy] do
    member do
      put :soft_destroy
    end
  end
  
  # Categories (for subjects)
  resources :categories, only: [:index, :create, :update, :destroy]
  
  # Users
  resources :users do
    member do
      put :set_administrator
      put :set_wepion
      put :unset_wepion
      put :set_corrector
      put :unset_corrector
      put :destroydata
      put :take_skin
      put :change_group
      get :recup_password
      patch :change_password
      put :follow
      put :unfollow
      put :set_can_change_name
      put :unset_can_change_name
      put :set_whitelisted
      put :unset_whitelisted
      get :validate_name # only via JS
    end
    collection do
      get :groups
      get :correctors
      get :followed
      get :search
      get :validate_names
    end
    resources :sanctions, only: [:index, :new, :create]
  end
  
  # Paths relative to current user
  put '/leave_skin', to: 'users#leave_skin'
  patch '/accept_legal', to: 'users#accept_legal'
  put '/accept_code_of_conduct', to: 'users#accept_code_of_conduct'
  get '/notifs', to: 'users#notifs'
  get '/activate', to: 'users#activate'
  put '/set_follow_message', to: "users#set_follow_message"
  get '/unset_follow_message', to: "users#unset_follow_message" # Get because it should be doable via email link
  patch '/improve_password', to: 'users#improve_password'
  
  # Paths relative to no user (yet)
  get '/signup', to: 'users#new'
  get '/forgot_password', to: 'users#forgot_password'
  post '/password_forgotten', to: 'users#password_forgotten'
  
  # Privacy policies
  resources :privacypolicies, only: [:index, :show, :new, :edit, :update, :destroy] do
    member do
      put :put_online
      get :edit_description
      patch :update_description
    end
    collection do
      get :last
    end
  end
  
  # Pictures
  resources :pictures, only: [:index, :show, :new, :create, :destroy] do
    member do
      get :image
    end
  end
  
  # Actualities
  resources :actualities, only: [:update, :edit, :destroy, :new, :create]
  
  # Attached files
  resources :myfiles, only: [:show, :index] do
    member do
      put :fake_delete
    end
  end
  
  # Discussions
  resources :discussions, only: [:new, :show] do # 'show' via HTML or JS 
    member do
      put :unread
    end
    collection do
      get :show_all # only via JS
    end
  end
  
  # Tchatmessages
  resources :tchatmessages, only: [:create]
  
  # Colors
  resources :colors, only: [:index, :create, :update, :destroy]
  
  # Faqs
  resources :faqs, only: [:index, :new, :create, :edit, :update, :destroy] do
    member do
      put :order
    end
  end
  
  # Sanctions
  resources :sanctions, only: [:edit, :update, :destroy]
  
  # Savedreplies
  resources :savedreplies, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  
  # Puzzles (10 years)
  resources :puzzles, only: [:index, :new, :create, :edit, :update, :destroy] do
    member do
      put :order
      get :attempt # only via JS
    end
    collection do
      get :graph
    end
  end
  get '/ten_years', to: 'puzzles#main'
  
  # Corrector applications
  resources :correctorapplications, only: [:index, :show, :new, :create, :destroy] do
    member do
      patch :answer
    end
  end
  
  # Sessions (singular resource, to call destroy without an id!)
  resource :sessions, only: [:create, :destroy]
  get '/fast_sign_in', to: 'sessions#fast_create' # Only in test and development!
  
  # Static pages
  root to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/stats', to: 'static_pages#stats'

  # Redirections for important old page names
  get '/frequentation', to: redirect('/stats') # sometimes used in forum
  get '/remove_followingmessage', to: redirect('/unset_follow_message') # in old emails
  get '/remove_followingsubject', to: redirect { |params, request| "/subjects/#{request.params[:subject_id]}/unfollow" } # in old emails
  get '/remove_followingcontest', to: redirect { |params, request| "/contests/#{request.params[:contest_id]}/unfollow" } # in old emails
  
  # Redirect all kinds of apple-touch-icon...png requests to the same icon
  get '/:apple_touch_icon' => redirect('/icon-120.png'), constraints: { apple_touch_icon: /apple-touch-icon(-\d+x\d+)?(-precomposed)?\.png/ }

  # Error pages
  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unacceptable'
  get '/500', to: 'errors#internal_error'
  get '*unmatched_route', to: 'errors#not_found', constraints: lambda { |req| req.path.exclude? 'rails/active_storage' }

end

app/models/contestsolution.rb
#encoding: utf-8

# == Schema Information
#
# Table name: contestsolutions
#
#  id                :integer          not null, primary key
#  contestproblem_id :integer
#  user_id           :integer
#  content           :text
#  official          :boolean          default(FALSE)
#  star              :boolean          default(FALSE)
#  reservation       :integer          default(0)
#  corrected         :boolean          default(FALSE)
#  score             :integer          default(-1)
#
include ApplicationHelper

class Contestsolution < ActiveRecord::Base

  # BELONGS_TO, HAS_MANY

  belongs_to :contestproblem
  belongs_to :user, optional: true
  has_one :contestcorrection, dependent: :destroy
  
  has_many :myfiles, as: :myfiletable, dependent: :destroy
  has_many :fakefiles, as: :fakefiletable, dependent: :destroy

  # VALIDATIONS

  validates :contestproblem_id, uniqueness: { scope: :user_id }
  validates :content, presence: true, length: { maximum: 16000 } # Limited to 8000 in the form but end-of-lines count twice
  validates :score, presence: true, inclusion: { in: [-1, 0, 1, 2, 3, 4, 5, 6, 7] }
  
  # BEFORE, AFTER
  
  after_create :create_correction
  
  # OTHER METHODS
  
  # Give the icon for the solution
  def icon
    if !corrected
      return dash_icon
    else
      if star
        return star_icon
      elsif score == 7
        return v_icon
      else
        return x_icon
      end
    end
  end
  
  # Tell if the solution can be seen by the given user
  def can_be_seen_by(user)
    return true if user.root?                                                     # Roots can see all solutions
    contestproblem = self.contestproblem
    contest = contestproblem.contest
    if contest.is_organized_by(user)                                              # For organizers:
      return true if self.official?                                               # - They can always see the official solution
      return true if contestproblem.at_least(:in_correction)                      # - They can see all user solutions when problem is in correction
    else                                                                          # For other users:
      return true if self.user == user && contestproblem.at_least(:in_correction) # - They can see their own solution, whatever the score, when time is finished
      return true if self.score == 7 && contestproblem.at_least(:corrected)       # - They can see other solutions with score 7, when correction is over
    end
    return false
  end
  
  private
  
  # Create the correction just after the creation
  def create_correction
    Contestcorrection.create(:contestsolution => self, :content => "")
  end

end

app/controllers/contestsolutions_controller.rb
#encoding: utf-8
class ContestsolutionsController < ApplicationController
  include ContestConcern
  include FileConcern
  
  skip_before_action :error_if_invalid_csrf_token, only: [:create, :update] # Do not forget to check @invalid_csrf_token instead!
  
  before_action :signed_in_user_danger, only: [:create, :update, :destroy, :reserve, :unreserve]
  
  before_action :check_contests, only: [:create, :update, :destroy]
  
  before_action :get_contestsolution, only: [:show, :update, :destroy, :reserve, :unreserve]
  before_action :get_contestproblem, only: [:show, :create]
  
  before_action :contestsolution_of_contestproblem, only: [:show]
  before_action :user_can_see_solution, only: [:show]
  before_action :author_of_solution, only: [:update]
  before_action :user_can_send_solution, only: [:create, :update]
  before_action :user_can_write_submission, only: [:create]
  before_action :user_can_delete_solution, only: [:destroy]
  before_action :organizer_of_contest, only: [:reserve, :unreserve]
  before_action :solution_can_be_reserved, only: [:reserve, :unreserve]
  
  # Show a solution
  def show
  end

  # Create a solution (send the form)
  def create
    oldsol = @contestproblem.contestsolutions.where(:user => current_user).first
    if !oldsol.nil? # Can happen if we have two windows and we try to create twice a solution to a same problem
      @contestsolution = oldsol
      update and return
    end
  
    params[:contestsolution][:content].strip! if !params[:contestsolution][:content].nil?

    @contestsolution = @contestproblem.contestsolutions.build(content: params[:contestsolution][:content],
                                                              user:    current_user)
    
    # Save solution, handling usual errors
    if !save_object_handling_errors(@contestsolution, 'contestproblems/show')
      return
    end
    
    flash[:success] = "Solution enregistrée."
    redirect_to contestproblem_contestsolution_path(@contestproblem, @contestsolution)
  end

  # Update a solution (send the form)
  def update
    params[:contestsolution][:content].strip! if !params[:contestsolution][:content].nil?
    @contestsolution.content = params[:contestsolution][:content]
    
    # Save solution, handling usual errors
    if !save_object_handling_errors(@contestsolution, 'contestproblems/show')
      return
    end
    
    flash[:success] = "Solution enregistrée."
    redirect_to contestproblem_contestsolution_path(@contestproblem, @contestsolution)
  end

  # Delete a solution
  def destroy
    flash[:success] = "Solution supprimée."
    @contestsolution.destroy
    redirect_to contestproblem_path(@contestproblem)
  end
  
  # Reserve a solution
  def reserve
    if @contestsolution.reservation > 0 && @contestsolution.reservation != current_user.id
      @correct_name = User.find(@contestsolution.reservation).name
      @ok = 0
    else
      @contestsolution.update_attribute(:reservation, current_user.id)
      @ok = 1
    end
  end

  # Un-reserve a solution
  def unreserve
    @contestsolution.update_attribute(:reservation, 0)
  end

  private
  
  ########## GET METHODS ##########
  
  # Get the solution
  def get_contestsolution
    @contestsolution = Contestsolution.find_by_id(params[:id])
    return if check_nil_object(@contestsolution)
    @contestproblem = @contestsolution.contestproblem
    @contest = @contestproblem.contest
  end

  # Get the problem
  def get_contestproblem
    @contestproblem = Contestproblem.find_by_id(params[:contestproblem_id])
    return if check_nil_object(@contestproblem)
    @contest = @contestproblem.contest
  end
  
  ########## CHECK METHODS ##########
  
  # Check that solution belongs to problem
  def contestsolution_of_contestproblem
    if @contestsolution.contestproblem != @contestproblem
      render 'errors/access_refused'
    end
  end
  
  # Check that current user is the author of the solution
  def author_of_solution
    if @contestsolution.user != current_user
      render 'errors/access_refused'
    end
  end
  
  # Check if current user can see a solution
  def user_can_see_solution
    if !signed_in? || !@contestsolution.can_be_seen_by(current_user)
      redirect_to contestproblem_path(@contestproblem)
    end
  end
  
  # Check if current user can send a solution
  def user_can_send_solution
    if @contest.is_organized_by_or_admin(current_user) || current_user.rating < 200 || @contestproblem.at_most(:not_started_yet)
      render 'errors/access_refused' and return
    end
    if !@contestproblem.in_progress?
      flash[:danger] = "Vous ne pouvez plus enregistrer cette solution."
      redirect_to @contestproblem
    end
  end
  
  # Check if current user can delete a solution
  def user_can_delete_solution
    unless @contestproblem.in_progress? && !@contestsolution.official && @contestsolution.user == current_user && !in_skin?
      flash[:danger] = "Vous ne pouvez pas supprimer cette solution."
      redirect_to @contestproblem
    end
  end
  
  # Check if the solution can be reserved
  def solution_can_be_reserved
    if !@contestproblem.in_correction? && !@contestproblem.in_recorrection? && !@contestsolution.official?
      redirect_to @contestproblem
    end
  end
end

app/views/contestsolutions/_edit.html.erb
<%= form_for @contestsolution, :html => { :multipart => true } do |f| %>

  <%= render 'submissions/form', f: f %>
  <%= render 'shared/edit_files', s: @contestsolution %>

  <%= f.submit "Enregistrer", class: "btn btn-primary mb-2", :disabled => in_skin? %>
  <button class="btn btn-ld-light-dark mb-2" onclick="return Rolling.hideActual();">Annuler</button>
<% end %>

app/views/contestsolutions/_index.html.erb
<script type="text/javascript">
var showCorrect = function () {
  document.getElementById("btn_correct").style.display = 'none';
  document.getElementById("all_correct").style.display = 'table';
  document.getElementById("all_correct").style.width = 'auto';
}
var showFalse = function () {
  document.getElementById("btn_false").style.display = 'none';
  document.getElementById("all_false").style.display = 'table';
  document.getElementById("all_false").style.width = 'auto';
}
</script>

<!-- Cette page affiche toutes les solutions que l'utilisateur peut voir -->

<% mine_is_star = false %>

<!-- Votre solution -->
<% if !@contest.is_organized_by_or_admin(current_user) %>
  <% sol = @contestproblem.contestsolutions.where(:user => current_user).first %>
  <% if !sol.nil? %>
    <h3>Votre solution</h3>
    <table class="table table-bordered" style="width:auto;">
      <% if sol.star %>
        <% mine_is_star = true %>
      <% end %>
      <%= render 'contestsolutions/line', sol: sol, type: "mine" %>
    </table>
  <% end %>
<% end %>

<!-- Solutions étoilées + correctes (7/7) -->
<% if @contestproblem.at_least(:corrected) || @contest.is_organized_by_or_root(current_user) %>
  <h3>
  <% if mine_is_star %>
    Autres solutions étoilées
  <% else %>
    Solutions étoilées
  <% end %>
  </h3>
  <% starred = @contestproblem.contestsolutions.where("star = ? AND (official = ? OR user_id != ?)", true, true, current_user.id).order(:user_id).includes(:user) %>
  <% if starred.count > 0 %>
    <table class="table table-bordered" style="width:auto;">
    <% starred.each do |sol| %>
      <%= render 'contestsolutions/line', sol: sol, type: "starred" %>
    <% end %>
    </table>
  <% else %>
    <% if @contest.is_organized_by_or_root(current_user) %>
      <p>Aucune solution étoilée. <span class="text-color-orange">Il en faut au minimum une !</span></p>
    <% else %>
      <p>Aucune <%= "autre" if mine_is_star %> solution étoilée.</p>
    <% end %>
  <% end %>
  
  <h3>Autres solutions correctes</h3>
  <% good = @contestproblem.contestsolutions.where("star = ? AND score = ? AND corrected = ? AND (official = ? OR user_id != ?)", false, 7, true, true, current_user.id).order(:user_id).includes(:user) %>
  <% if good.count > 0 %>
    <p id="btn_correct"><%= link_to "Afficher les autres solutions correctes", "javascript:showCorrect()" %></p>
    <table class="table table-bordered fixed-scroll" style="width:auto; display:none;" id="all_correct">
    <tbody>
    <% good.each do |sol| %>
      <%= render 'contestsolutions/line', sol: sol, type: "good" %>
    <% end %>
    </tbody>
    </table>
  <% else %>
    <p>Aucune autre solution correcte.</p>
  <% end %>
<% end %>

<!-- Solutions erronées -->
<% if @contest.is_organized_by_or_root(current_user) %>
  <h3>Solutions erronées / non-publiques</h3>
  <% bad = @contestproblem.contestsolutions.where("score < 7 AND corrected = ?", true).order(:user_id).includes(:user) %>
  <% if bad.count > 0 %>
    <p id="btn_false"><%= link_to "Afficher les solutions erronées et non-publiques", "javascript:showFalse()" %></p>
    <table class="table table-bordered fixed-scroll" style="width:auto; display:none;" id="all_false">
    <tbody>
    <% bad.each do |sol| %>
      <%= render 'contestsolutions/line', sol: sol, type: "bad" %>
    <% end %>
    </tbody>
    </table>
  <% else %>
    <p>Aucune solution erronée.</p>
  <% end %>
<% end %>

<!-- Solutions non-corrigées - bouton "publier" -->
<% if @contestproblem.in_correction? && @contest.is_organized_by_or_root(current_user) %>
  <h3>Solutions à corriger</h3>
  <% tocorrect = @contestproblem.contestsolutions.where(:corrected => false).order(:user_id).all %>
  <% if tocorrect.count > 0 %>
    <table class="table table-bordered fixed-scroll" style="width:auto;">
    <tbody>
    <% tocorrect.each do |sol| %>
      <%= render 'contestsolutions/line', sol: sol, type: "tocorrect" %>
    <% end %>
    </tbody>
    </table>
  <% else %>
    <p>Aucune solution à corriger.</p>
    <% if @contestproblem.contestsolutions.where(:star => true).count == 0 %>
      <p class="text-center fst-italic">Il faut au minimum une solution étoilée pour publier les résultats.</p>
    <% else %>
      <p class="text-center">
        <%= link_to "Publier les résultats", publish_results_contestproblem_path(@contestproblem), :method => :put, class: 'btn btn-danger', data: { confirm: "Êtes-vous #{current_user.sure} de vouloir publier les corrections ? Attention ! Il ne sera plus possible de modifier les corrections après cela." } %>
      </p>
    <% end %>
  <% end %>
<% end %>

app/views/contestsolutions/_line.html.erb
<!-- Couleur -->
<% can_see_score = (sol.contestproblem.at_least(:corrected) || @contest.is_organized_by_or_root(current_user)) %>
<% if !sol.corrected || !can_see_score %>
  <% if @contest.is_organized_by_or_root(current_user) && (sol.contestproblem.in_correction? || sol.contestproblem.in_recorrection?) %>
    <% res = sol.reservation %>
    <% if res == 0 %>
      <% color_class = "table-ld-warning" %>
    <% elsif res == current_user.id %>
      <% color_class = "table-ld-warning-greener" %>
    <% else %>
      <% color_class = "table-ld-warning-reder" %>
    <% end %>
  <% else %>
    <% color_class="table-ld-warning" %>
  <% end %>
<% elsif sol.score == 7 %>
  <% color_class = "table-ld-success" %>
<% else %>
  <% color_class = "table-ld-danger" %>
<% end %>

<tr id="line_sol_<%= sol.id %>" class="<%= color_class %>">

<!-- Icone -->
<td class="text-center" style="width:50px;">
  <% if !can_see_score %>
    <%= image_tag dash_icon, :class => "svg-black-white" %>
  <% else %>
    <%= image_tag sol.icon, :class => "svg-black-white" %>
  <% end %>
</td>

<!-- Qui -->
<td id="user_<%= sol.id %>" style="width:200px;">
  <% if sol.official %>
    <b>Solution officielle</b>
  <% else %>
    <%= sol.user.linked_name %>
  <% end %>
</td>

<td id="score_<%= sol.id %>" class="text-center" style="width:40px;">
  <% if can_see_score && !sol.official? && sol.score >= 0 %>
    <%= sol.score %>
  <% else %>
    -
  <% end %>
</td>

<!-- Voir -->
<td class="text-center" style="width:56px;">
<%= link_to "Voir", contestproblem_contestsolution_path(sol.contestproblem, sol) %>
</td>

</tr>

app/views/contestsolutions/_new.html.erb
<%= form_for @contestsolution, url: contestproblem_contestsolutions_path(@contestproblem), :html => { :multipart => true } do |f| %>
  
  <%= render 'submissions/form', f: f %>
  <%= render 'shared/edit_files' %>

  <%= f.submit "Enregistrer", class: "btn btn-primary mb-2", :disabled => in_skin? %>
<% end %>

app/views/contestsolutions/_show_in_progress.html.erb
<h3>Votre solution <%= "(modifiable)" if !@contestsolution.new_record? %></h3>

<!-- Si un brouillon a déjà été enregistré -->
<% if !@contestsolution.new_record? %>
  <div id="the" class="content-part">
    <%= render 'shared/post', ms: @contestsolution, can_edit: true %>
  </div>
<% end %>

<div id="form" class="form-part px-1" style="<%= 'height:0px;' if !@contestsolution.new_record? %>">
<% if @contestsolution.new_record? %>
  <%= render 'contestsolutions/new' %>
<% else %>
  <%= render 'contestsolutions/edit' %>
<% end %>

<p class="fst-italic">
  Vous pouvez modifier votre solution jusqu'à la date limite de résolution du problème.
</p>
</div>

<% if @contestsolution.errors.any? %>
  <script>rollingDevelopQuickWhenPossible("")</script>
<% end %>

app/views/contestsolutions/show.html.erb
<%= render 'contestproblems/show' %>

<hr>

<h3>
<% if @contestsolution.official? %>
  Solution officielle
<% elsif @contestsolution.user == current_user %>
  Votre solution
  <% if @contestproblem.in_correction? %>
    (en attente de correction)
  <% end %>
<% else %>
  Solution de <%= raw @contestsolution.user.linked_name %>
<% end %>

<% if @contest.is_organized_by_or_root(current_user) %>
  <% if !@contestsolution.corrected %>
    (à corriger)
  <% elsif @contestsolution.official? %>
    <% if @contestsolution.score == 7 %>
      (publique)
    <% else %>
      (non-publique)
    <% end %>
  <% end %>
<% end %>
</h3>

<% if (@contestsolution.official? || @contestproblem.in_correction? || @contestproblem.in_recorrection?) && @contest.is_organized_by(current_user) %>
  <script type="text/javascript">
  var reserve = function () {
    $.getScript("<%= reserve_contestsolution_url(@contestsolution) %>");
  }
  var unreserve = function () {
    $.getScript("<%= unreserve_contestsolution_url(@contestsolution) %>");
  }
  </script>

  <% res = @contestsolution.reservation %>
  <div id="div_reserved_by_nobody" class="mb-2 p-2 ps-3 bg-as-table-ld-warning" style="<%= "display:none;" if res != 0 %>">
    Cliquez ici pour réserver.
    <button id="button-reserve" class="btn btn-ld-light-dark ms-5" onclick="javascript:reserve()" <%= "disabled" if in_skin? %>>Réserver</button>
  </div>

  <div id="div_reserved_by_other" class="mb-2 p-2 ps-3 bg-as-table-ld-warning-reder" style="<%= "display:none;" if res == 0 || res == current_user.id %>">
    Réservé par <b><%= res > 0 ? User.find(res).name : "" %></b>.
  </div>

  <div id="div_reserved_by_me" class="mb-2 p-2 ps-3 bg-as-table-ld-warning-greener" style="<%= "display:none;" if res != current_user.id %>">
    Cliquez ici pour annuler votre réservation.
    <button id="button-unreserve" class="btn btn-ld-light-dark ms-5" onclick="javascript:unreserve()" <%= "disabled" if in_skin? %>>Annuler</button>
  </div>
<% end %>

<!-- Affichage de la soumission -->
<% if !@contestsolution.official %>
  <%= render 'shared/post', ms: @contestsolution, can_edit: false %>
<% end %>

<% if @contestproblem.at_least(:corrected) || @contest.is_organized_by_or_root(current_user) %>
  <%= render 'contestcorrections/show', contestsolution: @contestsolution, contestcorrection: @contestsolution.contestcorrection %>
<% end %>