config/routes.rb
Rails.application.routes.draw do

  # Sections
  resources :sections, only: [:show, :edit, :update] do
    resources :chapters, only: [:new, :create]
    resources :problems, only: [:index, :new, :create]
  end

  # Chapters
  resources :chapters, only: [:show, :update, :edit, :destroy] do
    member do
      get :all
      put :put_online
      put :mark_submission_prerequisite
      put :unmark_submission_prerequisite
      put :order
      put :read
    end
    collection do
      get :stats
    end
    resources :theories, only: [:show, :new, :create]
    resources :questions, only: [:show, :new, :create]
  end

  # Prerequisites
  resources :prerequisites, only: [:index, :create, :destroy]

  # Theories
  resources :theories, only: [:update, :edit, :destroy] do
    member do
      put :order
      put :put_online
      put :read
      put :unread
    end
  end

  # Questions
  resources :questions, only: [:update, :edit, :destroy] do
    member do
      put :order
      put :put_online
      get :edit_explanation
      patch :update_explanation
      get :manage_items
      get :show_answer # only via JS
      get :hide_answer # only via JS
      get :check_answer # only via JS
    end
    resources :items, only: [:create]
  end
  
  # Items
  resources :items, only: [:update, :destroy] do
    member do
      put :correct
      put :uncorrect
      put :order
    end
  end
  
  # Problems
  resources :problems, only: [:update, :edit, :destroy, :show] do
    member do
      put :delete_prerequisite
      post :add_prerequisite
      put :order
      put :put_online
      get :edit_explanation
      get :edit_markscheme
      patch :update_explanation
      patch :update_markscheme
      post :add_virtualtest
      get :manage_externalsolutions
      get :mark_favorite # only via JS
      get :unmark_favorite # only via JS
      put :mark_reviewed
      put :unmark_reviewed
    end
    resources :submissions, only: [:show, :new, :create, :index] # 'index' only via JS
    resources :externalsolutions, only: [:create]
  end
  
  resources :solvedproblems, only: [:index]

  # Submissions
  resources :submissions, only: [:update, :destroy] do
    member do
      patch :send_draft
      put :read
      put :unread
      put :star
      put :unstar
      put :update_score
      put :mark_wrong
      put :mark_correct
      get :reserve # only via JS
      get :unreserve # only via JS
      post :search_script # only via JS
      get :next_good
      get :prev_good
    end
    collection do
      get :all
      get :allmy
      get :allnew
      get :allmynew
      get :allhidden
    end
    resources :corrections, only: [:create]
    resources :suspicions, only: [:create]
    resources :starproposals, only: [:create]
  end
  
  # External solutions
  resources :externalsolutions, only: [:update, :destroy] do
    resources :extracts, only: [:create]
  end
  
  # Extracts
  resources :extracts, only: [:update, :destroy]
  
  # Suspicions
  resources :suspicions, only: [:index, :destroy, :update]
  
  # Star proposals
  resources :starproposals, only: [:index, :destroy, :update]
  
  # Virtual tests
  resources :virtualtests do
    member do
      put :put_online
      put :begin_test
    end
  end
  
  # Contests
  resources :contests do
    member do
      put :put_online
      get :cutoffs
      post :define_cutoffs
      put :follow
      get :unfollow # Get because it should be doable via email link
      patch :add_organizer
      put :remove_organizer
    end
    resources :contestproblems, only: [:new, :create]
  end
  
  # Contest problems
  resources :contestproblems, only: [:show, :edit, :update, :destroy] do
    member do
      put :publish_results
      put :authorize_corrections
      put :unauthorize_corrections
    end
    resources :contestsolutions, only: [:show, :create]
  end
  
  # Contest solutions
  resources :contestsolutions, only: [:update, :destroy] do
    member do
      get :reserve # only via JS
      get :unreserve # only via JS
    end
  end
  
  # Contest corrections
  resources :contestcorrections, only: [:update]
  
  # Subjects
  resources :subjects, only: [:index, :show, :new, :create, :update, :destroy] do
    member do
      put :migrate
      put :follow
      get :unfollow # Get because it should be doable via email link
    end
    resources :messages, only: [:create]
  end
  
  # Messages
  resources :messages, only: [:update, :destroy] do
    member do
      put :soft_destroy
    end
  end
  
  # Categories (for subjects)
  resources :categories, only: [:index, :create, :update, :destroy]
  
  # Users
  resources :users do
    member do
      put :set_administrator
      put :set_wepion
      put :unset_wepion
      put :set_corrector
      put :unset_corrector
      put :destroydata
      put :take_skin
      put :change_group
      get :recup_password
      patch :change_password
      put :follow
      put :unfollow
      put :set_can_change_name
      put :unset_can_change_name
      put :set_whitelisted
      put :unset_whitelisted
      get :validate_name # only via JS
    end
    collection do
      get :groups
      get :correctors
      get :followed
      get :search
      get :validate_names
    end
    resources :sanctions, only: [:index, :new, :create]
  end
  
  # Paths relative to current user
  put '/leave_skin', to: 'users#leave_skin'
  patch '/accept_legal', to: 'users#accept_legal'
  put '/accept_code_of_conduct', to: 'users#accept_code_of_conduct'
  get '/notifs', to: 'users#notifs'
  get '/activate', to: 'users#activate'
  put '/set_follow_message', to: "users#set_follow_message"
  get '/unset_follow_message', to: "users#unset_follow_message" # Get because it should be doable via email link
  patch '/improve_password', to: 'users#improve_password'
  
  # Paths relative to no user (yet)
  get '/signup', to: 'users#new'
  get '/forgot_password', to: 'users#forgot_password'
  post '/password_forgotten', to: 'users#password_forgotten'
  
  # Privacy policies
  resources :privacypolicies, only: [:index, :show, :new, :edit, :update, :destroy] do
    member do
      put :put_online
      get :edit_description
      patch :update_description
    end
    collection do
      get :last
    end
  end
  
  # Pictures
  resources :pictures, only: [:index, :show, :new, :create, :destroy] do
    member do
      get :image
    end
  end
  
  # Actualities
  resources :actualities, only: [:update, :edit, :destroy, :new, :create]
  
  # Attached files
  resources :myfiles, only: [:show, :index] do
    member do
      put :fake_delete
    end
  end
  
  # Discussions
  resources :discussions, only: [:new, :show] do # 'show' via HTML or JS 
    member do
      put :unread
    end
    collection do
      get :show_all # only via JS
    end
  end
  
  # Tchatmessages
  resources :tchatmessages, only: [:create]
  
  # Colors
  resources :colors, only: [:index, :create, :update, :destroy]
  
  # Faqs
  resources :faqs, only: [:index, :new, :create, :edit, :update, :destroy] do
    member do
      put :order
    end
  end
  
  # Sanctions
  resources :sanctions, only: [:edit, :update, :destroy]
  
  # Savedreplies
  resources :savedreplies, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  
  # Puzzles (10 years)
  resources :puzzles, only: [:index, :new, :create, :edit, :update, :destroy] do
    member do
      put :order
      get :attempt # only via JS
    end
    collection do
      get :graph
    end
  end
  get '/ten_years', to: 'puzzles#main'
  
  # Corrector applications
  resources :correctorapplications, only: [:index, :show, :new, :create, :destroy] do
    member do
      patch :answer
    end
  end
  
  # Sessions (singular resource, to call destroy without an id!)
  resource :sessions, only: [:create, :destroy]
  get '/fast_sign_in', to: 'sessions#fast_create' # Only in test and development!
  
  # Static pages
  root to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/stats', to: 'static_pages#stats'

  # Redirections for important old page names
  get '/frequentation', to: redirect('/stats') # sometimes used in forum
  get '/remove_followingmessage', to: redirect('/unset_follow_message') # in old emails
  get '/remove_followingsubject', to: redirect { |params, request| "/subjects/#{request.params[:subject_id]}/unfollow" } # in old emails
  get '/remove_followingcontest', to: redirect { |params, request| "/contests/#{request.params[:contest_id]}/unfollow" } # in old emails
  
  # Redirect all kinds of apple-touch-icon...png requests to the same icon
  get '/:apple_touch_icon' => redirect('/icon-120.png'), constraints: { apple_touch_icon: /apple-touch-icon(-\d+x\d+)?(-precomposed)?\.png/ }

  # Error pages
  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unacceptable'
  get '/500', to: 'errors#internal_error'
  get '*unmatched_route', to: 'errors#not_found', constraints: lambda { |req| req.path.exclude? 'rails/active_storage' }

end

app/models/savedreply.rb
#encoding: utf-8

# == Schema Information
#
# Table name: savedreplies
#
#  id         :bigint           not null, primary key
#  problem_id :bigint
#  content    :text
#  nb_uses    :integer          default(0)
#  section_id :bigint
#  approved   :boolean
#  user_id    :bigint
#

class Savedreply < ActiveRecord::Base

  # BELONGS_TO, HAS_MANY

  belongs_to :section, optional: true
  belongs_to :problem, optional: true
  belongs_to :user, optional: true

  # VALIDATIONS

  validates :section_id, presence: true # can be 0
  validates :problem_id, presence: true # can be 0
  validates :user_id, presence: true # can be 0
  validates :content, presence: true, length: { maximum: 8000 }
  validates :nb_uses, presence: true, numericality: { greater_than_or_equal_to: 0 }

end

app/controllers/savedreplies_controller.rb
#encoding: utf-8
class SavedrepliesController < ApplicationController
  before_action :signed_in_user, only: [:index, :show, :new, :edit]
  before_action :signed_in_user_danger, only: [:create, :update, :destroy]
  before_action :root_user, only: [:index, :show]
  before_action :corrector_user, only: [:new, :create]
  
  before_action :get_savedreply, only: [:show, :edit, :update, :destroy]
  before_action :get_submission, only: [:new, :create, :edit, :update]
  
  before_action :user_can_update_savedreply, only: [:edit, :update, :destroy]
  
  # Show non approved saved replies
  def index
  end
  
  # Show a submission where this saved reply can be seen
  def show
    redirect_to root_path if @savedreply.user_id != 0 # This method should not be used for personal saved replies
    if @savedreply.section_id == 0 && @savedreply.problem_id == 0
      submission = Submission.where.not(:status => [:closed, :plagiarized, :draft]).order(:created_at).last
    elsif @savedreply.section_id > 0
      submission = Submission.joins(:problem).where.not(:status => [:closed, :plagiarized, :draft]).where("problems.section_id = ?", @savedreply.section_id).order(:created_at).last
    else
      submission = Submission.where.not(:status => [:closed, :plagiarized, :draft]).where(:problem_id => @savedreply.problem_id).order(:created_at).last
    end
    redirect_to (submission.nil? ? root_path : problem_submission_path(submission.problem, submission))
  end
  
  # Create a saved reply (show the form)
  def new
    @savedreply = Savedreply.new(:problem => @submission.problem, :section => @submission.problem.section, :user_id => 0)
  end

  # Update a saved reply (show the form)
  def edit
    if !@savedreply.approved
      @savedreply.content = @savedreply.content.split("\n").drop(2).join("\n")
    end
  end
  
  # Create a saved reply (send the form)
  def create
    @savedreply = Savedreply.new(params.require(:savedreply).permit(:content))
    set_problem_or_section_or_user
    @savedreply.approved = current_user.root? || @savedreply.user_id > 0
    if @savedreply.save
      if !@savedreply.approved
        @savedreply.update_attribute(:content, "(Proposé par #{current_user.name})\n\n" + @savedreply.content)
      end
      flash[:success] = "Réponse ajoutée."
      redirect_to problem_submission_path(@submission.problem, @submission)
    else
      render 'new'
    end
  end

  # Update a saved reply (send the form)
  def update
    @savedreply.content = params[:savedreply][:content]
    set_problem_or_section_or_user
    @savedreply.approved = current_user.root? || @savedreply.user_id > 0
    if @savedreply.save
      if !@savedreply.approved
        @savedreply.update_attribute(:content, "(Proposé par #{current_user.name})\n\n" + @savedreply.content)
      end
      flash[:success] = "Réponse modifiée."
      redirect_to problem_submission_path(@submission.problem, @submission)
    else
      render 'edit'
    end
  end

  # Delete a saved reply
  def destroy
    @savedreply.destroy
    flash[:success] = "Réponse supprimée."
    redirect_back(fallback_location: root_path)
  end
  
  private
  
  ########## GET METHODS ##########
  
  # Get the saved reply
  def get_savedreply
    @savedreply = Savedreply.find_by_id(params[:id])
    return if check_nil_object(@savedreply)
  end
  
  # Get the submission we come from (to redirect to it at the end)
  def get_submission
    @submission = Submission.find_by_id(params[:sub])
    return if check_nil_object(@submission)
  end
  
  ########## CHECK METHODS ##########
  
  # Check that current user can update this saved reply
  def user_can_update_savedreply
    unless current_user.root? || @savedreply.user == current_user
      render 'errors/access_refused'
    end
  end
  
  ########## HELPER METHODS ##########
  
  def set_problem_or_section_or_user
    @savedreply.problem_id = 0
    @savedreply.section_id = 0
    @savedreply.user_id = 0
    problem_id = params[:savedreply][:problem_id].to_i
    if problem_id > 0 # Saved reply specific to a problem
      problem = Problem.find_by_id(problem_id)
      unless problem_id.nil?
        @savedreply.problem = problem
      end
    elsif problem_id < -1 # Saved reply specific to a section
      @savedreply.section_id = -1-problem_id
    elsif problem_id == -1 # Generic personal saved reply
      @savedreply.user = current_user
    end
  end
end

app/views/savedreplies/_form.html.erb
<%= render 'shared/error_messages', object: f.object %>

<% p = @submission.problem %>
<% listeprob = Array.new %>
<% listeprob.push(["Générique", 0]) %>
<% listeprob.push(["Générique (personnelle)", -1]) %>
<% listeprob.push([p.section.name, -1-p.section_id]) %>
<% listeprob.push(["Problème ##{p.number}", p.id]) %>

<!-- Problème -->
<div class="mb-2">
  <%= f.label :problem_id, :class => "form-label" %>
  <% if @savedreply.problem_id > 0 %>
    <% selected = @savedreply.problem_id %>
  <% elsif @savedreply.section_id > 0 %>
    <% selected = -1-@savedreply.section_id %>
  <% elsif @savedreply.user_id > 0 %>
    <% selected = -1 %>
  <% else %>
    <% selected = 0 %>
  <% end %>
  <%= f.select(:problem_id, options_for_select(listeprob, selected), {}, { :class => "form-select", :style => "width:100%; max-width:400px;" }) %>
</div>

<!-- Texte -->
<div class="mb-2">
  <%= f.label :content, :class => "form-label", :for => "MathInput" %>
  <%= render 'shared/preview' %>
  <%= render 'shared/smiley' %>
  <%= f.text_area :content, :class => "form-control", :maxlength => "8000", :style => "height:200px;", :id => "MathInput", :placeholder => "Vous pouvez utiliser \"[e]\" pour un mot concernant l'étudiant(e) qui ne prend un \"e\" qu'au féminin. La réponse s'adaptera automatiquement à l'étudiant(e)." %>
  <script>initAndUpdatePreviewSafeWhenPossible()</script>
</div>

app/views/savedreplies/_index.html.erb
<script type="text/javascript">
  var savedreplies_used = new Set();
  var cleanSavedReplies = function () {
    var to_hide = document.getElementsByClassName("to-hide");
    for (let i = 0; i < to_hide.length; i++) {
      to_hide[i].style.display = 'none';
    }
  }
  var toggleSavedReplies = function (id) {
    var el = document.getElementById(id);
    var old = el.style.display;
    cleanSavedReplies();
    if (old == 'none') {
      el.style.display = 'block';
    }
  }
  var savedReplyUsed = function(id) {
    savedreplies_used.add(id);
    var hidden_field = document.getElementById("correction_savedreplies_used");
    hidden_field.value = Array.from(savedreplies_used).join(",")
    cleanSavedReplies();
  }
</script>

<% generic_savedreplies = Savedreply.where(:problem_id => 0, :section_id => 0, :user_id => 0).order("nb_uses DESC, id ASC").to_a %>
<% num_generic = generic_savedreplies.size %>
<% personal_savedreplies = current_user.savedreplies.order("nb_uses DESC, id ASC").to_a %>
<% num_personal = personal_savedreplies.size %>
<% section_savedreplies = @submission.problem.section.savedreplies.order("nb_uses DESC, id ASC").to_a %>
<% num_section = section_savedreplies.size %>
<% problem_savedreplies = @submission.problem.savedreplies.order("nb_uses DESC, id ASC").to_a %>
<% num_problem = problem_savedreplies.size %>

<%= link_to "#{num_personal} rép. perso.", "javascript:toggleSavedReplies('personal_saved_replies')", :class => "btn btn-sm btn-ld-light-dark mb-2" if num_personal > 0 %>
<%= link_to "#{num_generic} rép. gén.", "javascript:toggleSavedReplies('generic_saved_replies')", :class => "btn btn-sm btn-ld-light-dark mb-2" if num_generic > 0 %>
<%= link_to "#{num_section} rép. #{@submission.problem.section.short_abbreviation}", "javascript:toggleSavedReplies('section_saved_replies')", :class => "btn btn-sm btn-ld-light-dark mb-2" if num_section > 0 %>
<%= link_to "#{num_problem} rép. ##{@submission.problem.number}", "javascript:toggleSavedReplies('problem_saved_replies')", :class => "btn btn-sm btn-ld-light-dark mb-2" if num_problem > 0 %>
<%= link_to "+", new_savedreply_path(:sub => @submission), :class => "btn btn-sm btn-ld-light-dark mb-2" %>

<% if num_generic > 0 %>
  <div id="generic_saved_replies" class="to-hide" style="display:none;">
    <% generic_savedreplies.each do |r| %>
      <%= render "savedreplies/show", r: r %>
    <% end %>
  </div>
<% end %>

<% if num_personal > 0 %>
  <div id="personal_saved_replies" class="to-hide" style="display:none;">
    <% personal_savedreplies.each do |r| %>
      <%= render "savedreplies/show", r: r %>
    <% end %>
  </div>
<% end %>

<% if num_section > 0 %>
  <div id="section_saved_replies" class="to-hide" style="display:none;">
    <% section_savedreplies.each do |r| %>
      <%= render "savedreplies/show", r: r %>
    <% end %>
  </div>
<% end %>

<% if num_problem > 0 %>
  <div id="problem_saved_replies" class="to-hide" style="display:none;">
    <% problem_savedreplies.each do |r| %>
      <%= render "savedreplies/show", r: r %>
    <% end %>
  </div>
<% end %>

app/views/savedreplies/_show.html.erb
<div class="card text-bg-ld-light-dark <%= "border-warning" if !r.approved %> mb-2">
 <% final_content = r.content.gsub("[e]", (@submission.user.sex == 0 ? "" : "e")) %>
 <% final_content_no_proposal = (r.approved ? final_content : final_content.split("\n").drop(2).join("\n")) %>
  <div id="savedreply-<%= r.id %>" class="card-body" style="cursor:pointer; display:flex; flex-direction:row; gap:10px; justify-content:space-between;" onclick='Insert.insert("<%= escape_javascript(final_content_no_proposal) %>", "", "MathInput"); savedReplyUsed(<%= r.id %>);'>
    <div><%= bbcode(final_content) %></div>
    <div><span class="badge text-bg-secondary" title="Cette réponse <%= r.nb_uses == 0 ? "n'a jamais été utilisée" : "a été utilisée #{r.nb_uses} fois" %>."><%= r.nb_uses %></span></div>
  </div>
  <% if current_user.root? || r.user == current_user %>
    <div class="card-body text-center pt-0">
      <%= link_to "Modifier", edit_savedreply_path(r, :sub => @submission) %> |
      <%= link_to "Supprimer", r, :method => :delete, :class => "text-color-red", data: (Rails.env.test? ? {} : { confirm: "Êtes vous #{current_user.sure} de vouloir supprimer cette réponse ?" })  %>
    </div>
  <% end %>
</div>

app/views/savedreplies/edit.html.erb
<% provide(:title, 'Modifier une réponse') %>

<h1><%= title_submission(@submission, "Modifier une réponse") %></h1>

<%= form_for(@savedreply, url: savedreply_path(@savedreply, :action => :update, :sub => @submission)) do |f| %>
  <%= render 'form', f: f %>
  <%= f.submit "Modifier", class: "btn btn-lg btn-primary mb-3" %>
<% end %>

app/views/savedreplies/index.html.erb
<% provide(:title, 'Réponses enregistrées') %>

<h1><%= title_1("Réponses enregistrées") %></h1>

<ul>
<% last = [-1, -1] %>
<% Savedreply.includes(:section).includes(:problem).where(:approved => false).order("section_id, problem_id").each do |s| %>
  <% if last == [s.section_id, s.problem_id] %>
    <% next %>
  <% end %>
  <% last = [s.section_id, s.problem_id] %>
  <li>
  <% if s.section_id == 0 && s.problem_id == 0 %>
    <%= link_to "Générique", s %>
  <% elsif s.problem_id == 0 %>
    <%= link_to s.section.name, s %>
  <% else %>
    <%= link_to "Problème ##{s.problem.number}", s %>
  <% end %>
  </li>
<% end %>
</ul>

app/views/savedreplies/new.html.erb
<% provide(:title, 'Créer une réponse') %>

<h1><%= title_submission(@submission, "Créer une réponse") %></h1>

<%= form_for(@savedreply, url: savedreplies_path(:action => :create, :sub => @submission)) do |f| %>
  <%= render 'form', f: f %>
  <%= f.submit "Créer", class: "btn btn-lg btn-primary mb-3" %>
<% end %>