config/routes.rb
Rails.application.routes.draw do

  # Sections
  resources :sections, only: [:show, :edit, :update] do
    resources :chapters, only: [:new, :create]
    resources :problems, only: [:index, :new, :create]
  end

  # Chapters
  resources :chapters, only: [:show, :update, :edit, :destroy] do
    member do
      get :all
      put :put_online
      put :mark_submission_prerequisite
      put :unmark_submission_prerequisite
      put :order
      put :read
    end
    collection do
      get :stats
    end
    resources :theories, only: [:show, :new, :create]
    resources :questions, only: [:show, :new, :create]
  end

  # Prerequisites
  resources :prerequisites, only: [:index, :create, :destroy]

  # Theories
  resources :theories, only: [:update, :edit, :destroy] do
    member do
      put :order
      put :put_online
      put :read
      put :unread
    end
  end

  # Questions
  resources :questions, only: [:update, :edit, :destroy] do
    member do
      put :order
      put :put_online
      get :edit_explanation
      patch :update_explanation
      get :manage_items
      get :show_answer # only via JS
      get :hide_answer # only via JS
      get :check_answer # only via JS
    end
    resources :items, only: [:create]
  end
  
  # Items
  resources :items, only: [:update, :destroy] do
    member do
      put :correct
      put :uncorrect
      put :order
    end
  end
  
  # Problems
  resources :problems, only: [:update, :edit, :destroy, :show] do
    member do
      put :delete_prerequisite
      post :add_prerequisite
      put :order
      put :put_online
      get :edit_explanation
      get :edit_markscheme
      patch :update_explanation
      patch :update_markscheme
      post :add_virtualtest
      get :manage_externalsolutions
      get :mark_favorite # only via JS
      get :unmark_favorite # only via JS
      put :mark_reviewed
      put :unmark_reviewed
    end
    resources :submissions, only: [:show, :new, :create, :index] # 'index' only via JS
    resources :externalsolutions, only: [:create]
  end
  
  resources :solvedproblems, only: [:index]

  # Submissions
  resources :submissions, only: [:update, :destroy] do
    member do
      patch :send_draft
      put :read
      put :unread
      put :star
      put :unstar
      put :update_score
      put :mark_wrong
      put :mark_correct
      get :reserve # only via JS
      get :unreserve # only via JS
      post :search_script # only via JS
      get :next_good
      get :prev_good
    end
    collection do
      get :all
      get :allmy
      get :allnew
      get :allmynew
      get :allhidden
    end
    resources :corrections, only: [:create]
    resources :suspicions, only: [:create]
    resources :starproposals, only: [:create]
  end
  
  # External solutions
  resources :externalsolutions, only: [:update, :destroy] do
    resources :extracts, only: [:create]
  end
  
  # Extracts
  resources :extracts, only: [:update, :destroy]
  
  # Suspicions
  resources :suspicions, only: [:index, :destroy, :update]
  
  # Star proposals
  resources :starproposals, only: [:index, :destroy, :update]
  
  # Virtual tests
  resources :virtualtests do
    member do
      put :put_online
      put :begin_test
    end
  end
  
  # Contests
  resources :contests do
    member do
      put :put_online
      get :cutoffs
      post :define_cutoffs
      put :follow
      get :unfollow # Get because it should be doable via email link
      patch :add_organizer
      put :remove_organizer
    end
    resources :contestproblems, only: [:new, :create]
  end
  
  # Contest problems
  resources :contestproblems, only: [:show, :edit, :update, :destroy] do
    member do
      put :publish_results
      put :authorize_corrections
      put :unauthorize_corrections
    end
    resources :contestsolutions, only: [:show, :create]
  end
  
  # Contest solutions
  resources :contestsolutions, only: [:update, :destroy] do
    member do
      get :reserve # only via JS
      get :unreserve # only via JS
    end
  end
  
  # Contest corrections
  resources :contestcorrections, only: [:update]
  
  # Subjects
  resources :subjects, only: [:index, :show, :new, :create, :update, :destroy] do
    member do
      put :migrate
      put :follow
      get :unfollow # Get because it should be doable via email link
    end
    resources :messages, only: [:create]
  end
  
  # Messages
  resources :messages, only: [:update, :destroy] do
    member do
      put :soft_destroy
    end
  end
  
  # Categories (for subjects)
  resources :categories, only: [:index, :create, :update, :destroy]
  
  # Users
  resources :users do
    member do
      put :set_administrator
      put :set_wepion
      put :unset_wepion
      put :set_corrector
      put :unset_corrector
      put :destroydata
      put :take_skin
      put :change_group
      get :recup_password
      patch :change_password
      put :follow
      put :unfollow
      put :set_can_change_name
      put :unset_can_change_name
      put :set_whitelisted
      put :unset_whitelisted
      get :validate_name # only via JS
    end
    collection do
      get :groups
      get :correctors
      get :followed
      get :search
      get :validate_names
    end
    resources :sanctions, only: [:index, :new, :create]
  end
  
  # Paths relative to current user
  put '/leave_skin', to: 'users#leave_skin'
  patch '/accept_legal', to: 'users#accept_legal'
  put '/accept_code_of_conduct', to: 'users#accept_code_of_conduct'
  get '/notifs', to: 'users#notifs'
  get '/activate', to: 'users#activate'
  put '/set_follow_message', to: "users#set_follow_message"
  get '/unset_follow_message', to: "users#unset_follow_message" # Get because it should be doable via email link
  patch '/improve_password', to: 'users#improve_password'
  
  # Paths relative to no user (yet)
  get '/signup', to: 'users#new'
  get '/forgot_password', to: 'users#forgot_password'
  post '/password_forgotten', to: 'users#password_forgotten'
  
  # Privacy policies
  resources :privacypolicies, only: [:index, :show, :new, :edit, :update, :destroy] do
    member do
      put :put_online
      get :edit_description
      patch :update_description
    end
    collection do
      get :last
    end
  end
  
  # Pictures
  resources :pictures, only: [:index, :show, :new, :create, :destroy] do
    member do
      get :image
    end
  end
  
  # Actualities
  resources :actualities, only: [:update, :edit, :destroy, :new, :create]
  
  # Attached files
  resources :myfiles, only: [:show, :index] do
    member do
      put :fake_delete
    end
  end
  
  # Discussions
  resources :discussions, only: [:new, :show] do # 'show' via HTML or JS 
    member do
      put :unread
    end
    collection do
      get :show_all # only via JS
    end
  end
  
  # Tchatmessages
  resources :tchatmessages, only: [:create]
  
  # Colors
  resources :colors, only: [:index, :create, :update, :destroy]
  
  # Faqs
  resources :faqs, only: [:index, :new, :create, :edit, :update, :destroy] do
    member do
      put :order
    end
  end
  
  # Sanctions
  resources :sanctions, only: [:edit, :update, :destroy]
  
  # Savedreplies
  resources :savedreplies, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  
  # Puzzles (10 years)
  resources :puzzles, only: [:index, :new, :create, :edit, :update, :destroy] do
    member do
      put :order
      get :attempt # only via JS
    end
    collection do
      get :graph
    end
  end
  get '/ten_years', to: 'puzzles#main'
  
  # Corrector applications
  resources :correctorapplications, only: [:index, :show, :new, :create, :destroy] do
    member do
      patch :answer
    end
  end
  
  # Sessions (singular resource, to call destroy without an id!)
  resource :sessions, only: [:create, :destroy]
  get '/fast_sign_in', to: 'sessions#fast_create' # Only in test and development!
  
  # Static pages
  root to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/stats', to: 'static_pages#stats'

  # Redirections for important old page names
  get '/frequentation', to: redirect('/stats') # sometimes used in forum
  get '/remove_followingmessage', to: redirect('/unset_follow_message') # in old emails
  get '/remove_followingsubject', to: redirect { |params, request| "/subjects/#{request.params[:subject_id]}/unfollow" } # in old emails
  get '/remove_followingcontest', to: redirect { |params, request| "/contests/#{request.params[:contest_id]}/unfollow" } # in old emails
  
  # Redirect all kinds of apple-touch-icon...png requests to the same icon
  get '/:apple_touch_icon' => redirect('/icon-120.png'), constraints: { apple_touch_icon: /apple-touch-icon(-\d+x\d+)?(-precomposed)?\.png/ }

  # Error pages
  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unacceptable'
  get '/500', to: 'errors#internal_error'
  get '*unmatched_route', to: 'errors#not_found', constraints: lambda { |req| req.path.exclude? 'rails/active_storage' }

end

app/models/theory.rb
# == Schema Information
#
# Table name: theories
#
#  id         :integer          not null, primary key
#  title      :string
#  content    :text
#  chapter_id :integer
#  position   :integer
#  online     :boolean          default(FALSE)
#
include ApplicationHelper

class Theory < ActiveRecord::Base

  # BELONGS_TO, HAS_MANY

  belongs_to :chapter
  has_and_belongs_to_many :users

  # VALIDATIONS

  validates :title, presence: true, length: { maximum: 255 }
  validates :content, presence: true, length: { maximum: 16000 }
  validates :position, presence: true, numericality: { greater_than_or_equal_to: 0 }

end

app/controllers/theories_controller.rb
#encoding: utf-8
class TheoriesController < ApplicationController
  include ChapterConcern
  
  before_action :signed_in_user, only: [:new, :edit]
  before_action :signed_in_user_danger, only: [:create, :update, :destroy, :put_online, :order, :read, :unread]
  before_action :admin_user, only: [:put_online]
  
  before_action :get_theory, only: [:show, :edit, :update, :destroy, :put_online, :order, :read, :unread]
  before_action :get_chapter, only: [:show, :new, :create]
  
  before_action :theory_of_chapter, only: [:show]
  before_action :user_can_see_chapter, only: [:show]
  before_action :user_can_see_theory, only: [:show]
  before_action :user_can_update_chapter, only: [:new, :edit, :create, :update, :destroy, :order]
  
  # Show a theory (inside the chapter)
  def show
  end

  # Create a theory (show the form)
  def new
    @theory = Theory.new
  end

  # Update a theory (show the form)
  def edit
  end

  # Create a theory (send the form)
  def create
    @theory = Theory.new(:title => params[:theory][:title], :content => params[:theory][:content], :online => false, :chapter => @chapter)
    if @chapter.theories.empty?
      @theory.position = 1
    else
      need = @chapter.theories.order('position').last
      @theory.position = need.position + 1
    end
    if @theory.save
      flash[:success] = "Point théorique ajouté."
      redirect_to chapter_theory_path(@chapter, @theory)
    else
      render 'new'
    end
  end

  # Update a theory (send the form)
  def update
    @theory.title = params[:theory][:title]
    @theory.content = params[:theory][:content]
    if @theory.save
      flash[:success] = "Point théorique modifié."
      redirect_to chapter_theory_path(@chapter, @theory)
    else
      render 'edit'
    end
  end

  # Delete a theory
  def destroy
    @theory.destroy
    flash[:success] = "Point théorique supprimé."
    redirect_to @chapter
  end

  # Put a theory online
  def put_online
    @theory.update_attribute(:online, true)
    redirect_to chapter_theory_path(@chapter, @theory)
  end
  
  # Move a theory to another position
  def order
    theory2 = @chapter.theories.where("position = ?", params[:new_position]).first
    if !theory2.nil? && theory2 != @theory
      res = swap_position(@theory, theory2)
      flash[:success] = "Point théorique déplacé#{res}." 
    end
    redirect_to chapter_theory_path(@chapter, @theory)
  end

  # Mark a theory as read
  def read
    current_user.theories << @theory
    redirect_to chapter_theory_path(@chapter, @theory)
  end

  # Mark a theory as unread
  def unread
    current_user.theories.delete(@theory)
    redirect_to chapter_theory_path(@chapter, @theory)
  end

  private
  
  ########## GET METHODS ##########
  
  # Get the theory
  def get_theory
    @theory = Theory.find_by_id(params[:id])
    return if check_nil_object(@theory)
    @chapter = @theory.chapter
  end
  
  # Get the chapter
  def get_chapter
    @chapter = Chapter.find_by_id(params[:chapter_id])
    return if check_nil_object(@chapter)
    @section = @chapter.section
  end
  
  ########## CHECK METHODS ##########
  
  # Check that theory belongs to chapter
  def theory_of_chapter
    if @theory.chapter != @chapter
      render 'errors/access_refused'
    end
  end
  
  # Check that user can see the theory
  def user_can_see_theory
    if !@theory.online && !user_can_write_chapter(current_user, @chapter)
      render 'errors/access_refused'
    end
  end
end

app/views/theories/_form.html.erb
<%= render 'shared/error_messages', object: f.object %>

<div class="mb-2">
  <%= f.label :title, :class => "form-label" %>
  <%= f.text_field :title, :class => "form-control", :style => "width:100%; max-width:400px;" %>
</div>

<div class="mb-2">
  <%= f.label :content, :for => "MathInput", :class => "form-label" %>
  <%= render 'shared/preview' %>
  <%= render 'shared/font' %>
  <%= f.text_area :content, :class => "form-control", :maxlength => "16000", :style => "height:250px;", :id => "MathInput" %>
  <script>initAndUpdatePreviewWhenPossible()</script>
</div>

app/views/theories/edit.html.erb
<% provide(:title, 'Modifier un point théorique') %>

<h1><%= title_theory(@theory, "Modifier un point théorique") %></h1>

<%= form_for(@theory) do |f| %>
  <%= render 'form', f: f %>
  <%= f.submit "Modifier", class: "btn btn-lg btn-primary mb-3" %>
<% end %>

app/views/theories/new.html.erb
<% provide(:title, 'Créer un point théorique') %>

<h1><%= title_chapter(@chapter, "Créer un point théorique") %></h1>

<%= form_for(@theory, url: chapter_theories_path) do |f| %>
  <%= render 'form', f: f %>
  <%= f.submit "Créer", class: "btn btn-lg btn-primary mb-3" %>
<% end %>

app/views/theories/show.html.erb
<%= render 'chapters/before', active: 'theory-' + @theory.id.to_s %>

<h3><%= @theory.title %></h3>
<div class="mb-3">
  <%= process_latex_test(htmlise(@theory.content), 0) %>
</div>

<div class="noprint">
<!-- Si administrateur ou hors-ligne (pour étudiant créateur) -->
<% if !@chapter.online? || (signed_in? && current_user.admin?) %>
  <p class="text-center">
  <!-- Modifier/Supprimer -->
    <%= link_to "Modifier ce point théorique", edit_theory_path(@theory) %> |
    <%= link_to "Supprimer ce point théorique", @theory, method: :delete, data: { confirm: "Êtes-vous #{current_user.sure} de vouloir supprimer ce point théorique ?" } %>
  </p>
  
  <!-- Déplacer -->
  <% theory_before = @chapter.theories.where("position < ?", @theory.position).order("position").last %>
  <% theory_after = @chapter.theories.where("position > ?", @theory.position).order("position").first %>

  <% if !theory_before.nil? || !theory_after.nil? %>
    <p class="text-center">
    Déplacer ce point théorique vers le
    <%= link_to "haut", order_theory_path(@theory, :new_position => theory_before.position), :method => :put if !theory_before.nil? %>
    <%= '-' if !theory_before.nil? && !theory_after.nil? %>
    <%= link_to "bas", order_theory_path(@theory, :new_position => theory_after.position), :method => :put if !theory_after.nil? %>
    </p>
  <% end %>
  
  <!-- Mettre en ligne -->
  <% if !@theory.online && @chapter.online %>
    <p class="text-center">
      <%= link_to "Mettre en ligne", put_online_theory_path(@theory), method: :put, class: 'btn btn-danger', data: { confirm: "Êtes-vous #{current_user.sure} de vouloir rendre ce point théorique visible par les utilisateurs ?" } %>
    </p>
  <% end %>

<!-- Si étudiant (connecté) -->
<% elsif signed_in? %>
  <p class="text-center">
    <% if !@read_theories.nil? && @read_theories.include?(@theory.id) %>
      <%= link_to "Marquer comme non lu", unread_theory_path(@theory), method: :put, class: "btn btn-ld-light-dark #{'disabled' if in_skin?}" %>
    <% else %>
      <%= link_to "Marquer comme lu", read_theory_path(@theory), method: :put, class: "btn btn-ld-light-dark #{'disabled' if in_skin?}" %>
    <% end %>
  </p>

  <hr class="bottom-help mt-0" />
  <p>Une question concernant ce point théorique ? N'hésitez pas à demander de l'aide sur le <%= link_to "forum", subjects_path(:q => "cha-" + @chapter.id.to_s), :target => "_blank" %> !</p>
<% end %>
</div>

<%= render 'chapters/after' %>