config/routes.rb
Rails.application.routes.draw do

  # Sections
  resources :sections, only: [:show, :edit, :update] do
    resources :chapters, only: [:new, :create]
    resources :problems, only: [:index, :new, :create]
  end

  # Chapters
  resources :chapters, only: [:show, :update, :edit, :destroy] do
    member do
      get :all
      put :put_online
      put :mark_submission_prerequisite
      put :unmark_submission_prerequisite
      put :order
      put :read
    end
    collection do
      get :stats
    end
    resources :theories, only: [:show, :new, :create]
    resources :questions, only: [:show, :new, :create]
  end

  # Prerequisites
  resources :prerequisites, only: [:index, :create, :destroy]

  # Theories
  resources :theories, only: [:update, :edit, :destroy] do
    member do
      put :order
      put :put_online
      put :read
      put :unread
    end
  end

  # Questions
  resources :questions, only: [:update, :edit, :destroy] do
    member do
      put :order
      put :put_online
      get :edit_explanation
      patch :update_explanation
      get :manage_items
      get :show_answer # only via JS
      get :hide_answer # only via JS
      get :check_answer # only via JS
    end
    resources :items, only: [:create]
  end
  
  # Items
  resources :items, only: [:update, :destroy] do
    member do
      put :correct
      put :uncorrect
      put :order
    end
  end
  
  # Problems
  resources :problems, only: [:update, :edit, :destroy, :show] do
    member do
      put :delete_prerequisite
      post :add_prerequisite
      put :order
      put :put_online
      get :edit_explanation
      get :edit_markscheme
      patch :update_explanation
      patch :update_markscheme
      post :add_virtualtest
      get :manage_externalsolutions
      get :mark_favorite # only via JS
      get :unmark_favorite # only via JS
      put :mark_reviewed
      put :unmark_reviewed
    end
    resources :submissions, only: [:show, :new, :create, :index] # 'index' only via JS
    resources :externalsolutions, only: [:create]
  end
  
  resources :solvedproblems, only: [:index]

  # Submissions
  resources :submissions, only: [:update, :destroy] do
    member do
      patch :send_draft
      put :read
      put :unread
      put :star
      put :unstar
      put :update_score
      put :mark_wrong
      put :mark_correct
      get :reserve # only via JS
      get :unreserve # only via JS
      post :search_script # only via JS
      get :next_good
      get :prev_good
    end
    collection do
      get :all
      get :allmy
      get :allnew
      get :allmynew
      get :allhidden
    end
    resources :corrections, only: [:create]
    resources :suspicions, only: [:create]
    resources :starproposals, only: [:create]
  end
  
  # External solutions
  resources :externalsolutions, only: [:update, :destroy] do
    resources :extracts, only: [:create]
  end
  
  # Extracts
  resources :extracts, only: [:update, :destroy]
  
  # Suspicions
  resources :suspicions, only: [:index, :destroy, :update]
  
  # Star proposals
  resources :starproposals, only: [:index, :destroy, :update]
  
  # Virtual tests
  resources :virtualtests do
    member do
      put :put_online
      put :begin_test
    end
  end
  
  # Contests
  resources :contests do
    member do
      put :put_online
      get :cutoffs
      post :define_cutoffs
      put :follow
      get :unfollow # Get because it should be doable via email link
      patch :add_organizer
      put :remove_organizer
    end
    resources :contestproblems, only: [:new, :create]
  end
  
  # Contest problems
  resources :contestproblems, only: [:show, :edit, :update, :destroy] do
    member do
      put :publish_results
      put :authorize_corrections
      put :unauthorize_corrections
    end
    resources :contestsolutions, only: [:show, :create]
  end
  
  # Contest solutions
  resources :contestsolutions, only: [:update, :destroy] do
    member do
      get :reserve # only via JS
      get :unreserve # only via JS
    end
  end
  
  # Contest corrections
  resources :contestcorrections, only: [:update]
  
  # Subjects
  resources :subjects, only: [:index, :show, :new, :create, :update, :destroy] do
    member do
      put :migrate
      put :follow
      get :unfollow # Get because it should be doable via email link
    end
    resources :messages, only: [:create]
  end
  
  # Messages
  resources :messages, only: [:update, :destroy] do
    member do
      put :soft_destroy
    end
  end
  
  # Categories (for subjects)
  resources :categories, only: [:index, :create, :update, :destroy]
  
  # Users
  resources :users do
    member do
      put :set_administrator
      put :set_wepion
      put :unset_wepion
      put :set_corrector
      put :unset_corrector
      put :destroydata
      put :take_skin
      put :change_group
      get :recup_password
      patch :change_password
      put :follow
      put :unfollow
      put :set_can_change_name
      put :unset_can_change_name
      put :set_whitelisted
      put :unset_whitelisted
      get :validate_name # only via JS
    end
    collection do
      get :groups
      get :correctors
      get :followed
      get :search
      get :validate_names
    end
    resources :sanctions, only: [:index, :new, :create]
  end
  
  # Paths relative to current user
  put '/leave_skin', to: 'users#leave_skin'
  patch '/accept_legal', to: 'users#accept_legal'
  put '/accept_code_of_conduct', to: 'users#accept_code_of_conduct'
  get '/notifs', to: 'users#notifs'
  get '/activate', to: 'users#activate'
  put '/set_follow_message', to: "users#set_follow_message"
  get '/unset_follow_message', to: "users#unset_follow_message" # Get because it should be doable via email link
  patch '/improve_password', to: 'users#improve_password'
  
  # Paths relative to no user (yet)
  get '/signup', to: 'users#new'
  get '/forgot_password', to: 'users#forgot_password'
  post '/password_forgotten', to: 'users#password_forgotten'
  
  # Privacy policies
  resources :privacypolicies, only: [:index, :show, :new, :edit, :update, :destroy] do
    member do
      put :put_online
      get :edit_description
      patch :update_description
    end
    collection do
      get :last
    end
  end
  
  # Pictures
  resources :pictures, only: [:index, :show, :new, :create, :destroy] do
    member do
      get :image
    end
  end
  
  # Actualities
  resources :actualities, only: [:update, :edit, :destroy, :new, :create]
  
  # Attached files
  resources :myfiles, only: [:show, :index] do
    member do
      put :fake_delete
    end
  end
  
  # Discussions
  resources :discussions, only: [:new, :show] do # 'show' via HTML or JS 
    member do
      put :unread
    end
    collection do
      get :show_all # only via JS
    end
  end
  
  # Tchatmessages
  resources :tchatmessages, only: [:create]
  
  # Colors
  resources :colors, only: [:index, :create, :update, :destroy]
  
  # Faqs
  resources :faqs, only: [:index, :new, :create, :edit, :update, :destroy] do
    member do
      put :order
    end
  end
  
  # Sanctions
  resources :sanctions, only: [:edit, :update, :destroy]
  
  # Savedreplies
  resources :savedreplies, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  
  # Puzzles (10 years)
  resources :puzzles, only: [:index, :new, :create, :edit, :update, :destroy] do
    member do
      put :order
      get :attempt # only via JS
    end
    collection do
      get :graph
    end
  end
  get '/ten_years', to: 'puzzles#main'
  
  # Corrector applications
  resources :correctorapplications, only: [:index, :show, :new, :create, :destroy] do
    member do
      patch :answer
    end
  end
  
  # Sessions (singular resource, to call destroy without an id!)
  resource :sessions, only: [:create, :destroy]
  get '/fast_sign_in', to: 'sessions#fast_create' # Only in test and development!
  
  # Static pages
  root to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/stats', to: 'static_pages#stats'

  # Redirections for important old page names
  get '/frequentation', to: redirect('/stats') # sometimes used in forum
  get '/remove_followingmessage', to: redirect('/unset_follow_message') # in old emails
  get '/remove_followingsubject', to: redirect { |params, request| "/subjects/#{request.params[:subject_id]}/unfollow" } # in old emails
  get '/remove_followingcontest', to: redirect { |params, request| "/contests/#{request.params[:contest_id]}/unfollow" } # in old emails
  
  # Redirect all kinds of apple-touch-icon...png requests to the same icon
  get '/:apple_touch_icon' => redirect('/icon-120.png'), constraints: { apple_touch_icon: /apple-touch-icon(-\d+x\d+)?(-precomposed)?\.png/ }

  # Error pages
  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unacceptable'
  get '/500', to: 'errors#internal_error'
  get '*unmatched_route', to: 'errors#not_found', constraints: lambda { |req| req.path.exclude? 'rails/active_storage' }

end

app/views/exercises/_explanation_fields.html.erb
<script src="/assets/preview.js"></script>
<script src="/assets/tainsert.js"></script>
<%= render 'shared/error_messages', object: f.object %>

<div class="well" id="MathPreview"></div>
<div class="well" id="MathBuffer" style="visibility:hidden; position:absolute; top:0; left: 0"></div>
<a href="#ici" onClick="JavaScript: TAinsert('<b>','</b>','MathInput'); Preview.Update();"><%= image_tag "bold.jpg", :title => "Gras", :style=>"margin-left:5px;" %></a>
<a href="#ici" onClick="JavaScript: TAinsert('<i>','</i>','MathInput'); Preview.Update();"><%= image_tag "italics.jpg", :title => "Italique" %></a>
<a href="#ici" onClick="JavaScript: TAinsert('<u>','</u>','MathInput'); Preview.Update();"><%= image_tag "underlined.jpg", :title => "Souligné" %></a>
<a href="#ici" onClick="JavaScript: TAinsert('<ul>\n<li>Point 1','</li>\n<li>Point 2</li>\n</ul>','MathInput'); Preview.Update();"><%= image_tag "list.jpg", :title => "Liste", :style=>"margin-left:15px;" %></a>
<a href="#ici" onClick="JavaScript: TAinsert('<ol>\n<li>Point 1','</li>\n<li>Point 2</li>\n</ol>','MathInput'); Preview.Update();"><%= image_tag "enumerate.jpg", :title => "Liste numérotée" %></a>
<a href="#ici" onClick="JavaScript: TAinsert('<a href=\'http://www.exemple.com\'>','</a>','MathInput'); Preview.Update();"><%= image_tag "link.jpg", :title => "Lien", :style=>"margin-left:15px;" %></a>
<a href="#ici" onClick="JavaScript: TAinsert('<center><img src=\'/system/pictures/0/votreImage.jpg\' width=\'600px\' /></center>','','MathInput'); Preview.Update();"><%= image_tag "picture.jpg", :title => "Image", :style=>"margin-right:50px;" %></a>
<%= link_to "Mes images", pictures_path, :target => "_blank" %> - <%= link_to "Uploader une image", new_picture_path, :target => "_blank" %>
<%= f.text_area :explanation, :class => "span12", :style => "height:200px; margin-top:5px;", :id=>"MathInput", :onkeyup => "Preview.Update()" %>

app/views/exercises/_fields.html.erb
<script src="/assets/preview.js"></script>
<script src="/assets/tainsert.js"></script>
<%= render 'shared/error_messages', object: f.object %>

<%= f.label "Enoncé" %>
<div class="well" id="MathPreview"></div>
<div class="well" id="MathBuffer" style="visibility:hidden; position:absolute; top:0; left: 0"></div>
<a href="#ici" onClick="JavaScript: TAinsert('<b>','</b>','MathInput'); Preview.Update();"><%= image_tag "bold.jpg", :title => "Gras", :style=>"margin-left:5px;" %></a>
<a href="#ici" onClick="JavaScript: TAinsert('<i>','</i>','MathInput'); Preview.Update();"><%= image_tag "italics.jpg", :title => "Italique" %></a>
<a href="#ici" onClick="JavaScript: TAinsert('<u>','</u>','MathInput'); Preview.Update();"><%= image_tag "underlined.jpg", :title => "Souligné" %></a>
<a href="#ici" onClick="JavaScript: TAinsert('<ul>\n<li>Point 1','</li>\n<li>Point 2</li>\n</ul>','MathInput'); Preview.Update();"><%= image_tag "list.jpg", :title => "Liste", :style=>"margin-left:15px;" %></a>
<a href="#ici" onClick="JavaScript: TAinsert('<ol>\n<li>Point 1','</li>\n<li>Point 2</li>\n</ol>','MathInput'); Preview.Update();"><%= image_tag "enumerate.jpg", :title => "Liste numérotée" %></a>
<a href="#ici" onClick="JavaScript: TAinsert('<a target=\'blank\' href=\'http://www.exemple.com\'>','</a>','MathInput'); Preview.Update();"><%= image_tag "link.jpg", :title => "Lien", :style=>"margin-left:15px;" %></a>
<a href="#ici" onClick="JavaScript: TAinsert('<figure><center><img src=\'/system/pictures/0/votreImage.jpg\' width=\'600px\' />\n\n<figcaption>Légende</figcaption></center></figure>','','MathInput'); Preview.Update();"><%= image_tag "picture.jpg", :title => "Image", :style=>"margin-right:50px;" %></a>
<%= link_to "Mes images", pictures_path, :target => "_blank" %> - <%= link_to "Uploader une image", new_picture_path, :target => "_blank" %>
<%= f.text_area :statement, :class => "span12", :style => "height:200px; margin-top:5px;", :id=>"MathInput", :onkeyup => "Preview.Update()" %>

<%= f.label "Réponse" %>
<%= f.text_field :answer, :class => "span2" %>

<label class="checkbox">
Cochez si la réponse est décimale
<%= f.check_box(:decimal) %>
</label>

app/views/exercises/_fields2.html.erb
<script src="/assets/preview.js"></script>
<script src="/assets/tainsert.js"></script>
<%= render 'shared/error_messages', object: f.object %>

<%= f.label "Enoncé" %>
<div class="well" id="MathPreview"></div>
<div class="well" id="MathBuffer" style="visibility:hidden; position:absolute; top:0; left: 0"></div>
<a href="#ici" onClick="JavaScript: TAinsert('<b>','</b>','MathInput'); Preview.Update();"><%= image_tag "bold.jpg", :title => "Gras", :style=>"margin-left:5px;" %></a>
<a href="#ici" onClick="JavaScript: TAinsert('<i>','</i>','MathInput'); Preview.Update();"><%= image_tag "italics.jpg", :title => "Italique" %></a>
<a href="#ici" onClick="JavaScript: TAinsert('<u>','</u>','MathInput'); Preview.Update();"><%= image_tag "underlined.jpg", :title => "Souligné" %></a>
<a href="#ici" onClick="JavaScript: TAinsert('<ul>\n<li>Point 1','</li>\n<li>Point 2</li>\n</ul>','MathInput'); Preview.Update();"><%= image_tag "list.jpg", :title => "Liste", :style=>"margin-left:15px;" %></a>
<a href="#ici" onClick="JavaScript: TAinsert('<ol>\n<li>Point 1','</li>\n<li>Point 2</li>\n</ol>','MathInput'); Preview.Update();"><%= image_tag "enumerate.jpg", :title => "Liste numérotée" %></a>
<a href="#ici" onClick="JavaScript: TAinsert('<a target=\'blank\' href=\'http://www.exemple.com\'>','</a>','MathInput'); Preview.Update();"><%= image_tag "link.jpg", :title => "Lien", :style=>"margin-left:15px;" %></a>
<a href="#ici" onClick="JavaScript: TAinsert('<figure><center><img src=\'/system/pictures/0/votreImage.jpg\' width=\'600px\' />\n\n<figcaption>Légende</figcaption></center></figure>','','MathInput'); Preview.Update();"><%= image_tag "picture.jpg", :title => "Image", :style=>"margin-right:50px;" %></a>
<%= link_to "Mes images", pictures_path, :target => "_blank" %> - <%= link_to "Uploader une image", new_picture_path, :target => "_blank" %>
<%= f.text_area :statement, :class => "span12", :style => "height:200px; margin-top:5px;", :id=>"MathInput", :onkeyup => "Preview.Update()" %>

<% if @exercise.chapter.online && @exercise.online %>
  <% if @exercise.decimal %>
    Réponse : <b><%= @exercise.answer %> (réponse décimale)</b><br/>
  <% else %>
    Réponse : <b><%= @exercise.answer.to_i %> (réponse entière)</b><br/>
  <% end %>
<% else %>
  <%= f.label "Réponse" %>
  <%= f.text_field :answer, :class => "span2" %>
  <label class="checkbox">
  Cochez si la réponse est décimale
  <%= f.check_box(:decimal) %>
  </label>
<% end %>

app/views/exercises/_show.html.erb
<!-- On vérifie que cet exercice peut bien être vu -->
<% if f.online || (@ss && current_user.sk.admin?) %>

<!-- Titre -->
<%= render 'exercises/title', f: f, number: number %>

<!-- Enoncé -->
<div>
  <%= raw(replace_indice(htmlise(f.statement))) %>
</div><br/>

<!-- Si administrateur -->
<% if @ss && current_user.sk.admin? %>

  <!-- Réponse -->
  <h4>Réponse</h4>
  <% if f.decimal %>
    <% vraidecimal = true %>
    <% if f.answer - f.answer.to_i <= 0.00001 && f.answer.to_i - f.answer <= 0.00001 %>
      <% vraidecimal = false %>
    <% end %>
    <span style="font-size:16px;"><%= f.answer if vraidecimal %><%= f.answer.to_i if !vraidecimal %></span> (On demande une réponse <b>décimale</b> au millième près)
  <% else %>
    <span style="font-size:16px;"><%= f.answer.to_i %></span> (On demande une réponse <b>entière</b>)
  <% end %>
  <br/><br/>
  
  <!-- Pour les admins -->
  <%= render 'exercises/admin', f: f, type: 2, number2: number2, number_tot: liste.size + liste2.size %>

<!-- Si étudiant inscrit -->
<% elsif @ss %>

  <% exo = Solvedexercise.where(:user_id => current_user.sk.id, :exercise_id => id) %>
  
  <!-- Si il y a déjà eu au moins un essai -->
  <% if exo.size > 0 %>
    <% exo = exo.first %>
    
    <!-- Si l'exercice est déjà résolu -->
    <% if exo.correct? %>
      <p style="color:green;"><b>
      <% if exo.nb_guess-1 > 0 %>
        Vous avez résolu cet exercice après <%= exo.nb_guess-1 %> erreur<%= "s" if exo.nb_guess-1 > 1 %>.
      <% else %>
        Vous avez résolu cet exercice du premier coup !
      <% end %>
      </b><br/><br/></p>
      
      <!-- Réponse -->
      <h4>Réponse</h4>
      <% if f.decimal %>
        <% vraidecimal = true %>
        <% if f.answer - f.answer.to_i <= 0.00001 && f.answer.to_i - f.answer <= 0.00001 %>
          <% vraidecimal = false %>
        <% end %>
        <span style="font-size:16px;"><%= f.answer if vraidecimal %><%= f.answer.to_i if !vraidecimal %></span> (On demande une réponse <b>décimale</b> au millième près)
      <% else %>
        <span style="font-size:16px;"><%= f.answer.to_i %></span> (On demande une réponse <b>entière</b>)
      <% end %>
      <% if f.explanation.size > 0 %>
        <br/><br/>
        
        <!-- Explication -->
        <h4>Explication</h4>
        <%= raw(htmlise(f.explanation)) %>
      <% end %>
      <br/>
      
    <!-- Si l'étudiant s'est déjà trompé -->
    <% else %>
      <%= render 'exercises/question', f: f, exo: exo %>
    <% end %>

  <!-- Si l'étudiant n'a pas encore essayé l'exercice -->
  <% else %>
  
    <% exo = Solvedexercise.new %>
    <%= render 'exercises/question', f: f, exo: exo %>
  <% end %>

  <hr style="border-top:1px dashed lightgray;" />
  Un souci avec cet exercice ? N'hésitez pas à demander de l'aide sur le <%= link_to "forum", subjects_path(:q => @chapter.id), :target => "_blank" %> !

<!-- Si étudiant non inscrit -->
<% else %>

  <% exo = Solvedexercise.new %>
  <%= render 'exercises/question', f: f, exo: exo %>
  
  <hr style="border-top:1px dashed lightgray;" />
  <center>Pour pouvoir répondre aux exercices, vous devez être connecté.</center>
<% end %>

<% end %>

app/views/exercises/explanation.erb
<% provide(:title, "Modifier l'explication d'un exercice".html_safe) %>
<h1>Modifier l'explication d'un exercice</h1>

<h3>Enoncé</h3>
<%= raw(@exercise.statement.gsub(/\\][ \r]*\n/,'\] ').gsub(/\$\$[ \r]*\n/,'$$ ').gsub(/<\/ol>[ \r]*\n/, '</ol>').gsub(/\n[ \r]*<\/ol>/, '</ol>').gsub(/<\/ul>[ \r]*\n/, '</ul>').gsub(/\n[ \r]*<\/ul>/, '</ul>').gsub(/\n[ \r]*<li>/, '<li>').gsub(/\n/, '<br/>')) %>

<br/>
<h3>Réponse</h3>
  <% if @exercise.decimal %>
    <b><%= @exercise.answer %></b> (On demande une réponse <b>décimale</b> au millième près)
  <% else %>
    <b><%= @exercise.answer.to_i %></b> (On demande une réponse <b>entière</b>)
  <% end %>
<br/>
<h3>Explication</h3>

<%= form_for(@exercise, url: exercise_update_explanation_path) do |f| %>
  <%= render 'explanation_fields', f: f %>
  <br />
  <%= f.submit "Modifier", class: "btn btn-large btn-primary" %>
<% end %>

<center><%= link_to 'Retour au chapitre', chapter_path(@exercise.chapter, :type => 2, :which => @exercise.id) %></center>

<script>
Preview.Init();
Preview.Update();
</script>